name: grpc-rest-solution

services:
  webapirest:
    image: ${DOCKER_REGISTRY-}webapirest
    build:
      context: .
      dockerfile: WebApiRest/Dockerfile
    # networks:
    #   - POC-GrpcRest

  grpcserviceserver:
    image: ${DOCKER_REGISTRY-}grpcserviceserver
    build:
      context: .
      dockerfile: GrpcServiceServer/Dockerfile
#     networks:
#       - POC-GrpcRest

# networks:
#   POC-GrpcRest:
#     driver: bridge

